local Forgeframe = CreateFrame("Frame")
Forgeframe:RegisterEvent("PLAYER_LOGIN")
Forgeframe:SetScript("OnEvent", function()
    InitializeTalentTree()
    InitializeTooltips()
    InitializeTransmog()
    initializeAllStats()
    InitInstance()
end)
